package io.github.dev_abdulhay.telegramauth.managedbots;

import jakarta.persistence.Column;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;

import java.time.OffsetDateTime;

/**
 * A stored managed-bot intent. {@code @MappedSuperclass} — host apps subclass
 * with {@code @Entity @Table(name = "...")}, exactly like {@link BaseManagedBot}.
 *
 * <p>The primary key is the intent id itself: it is generated by
 * {@code ManagedBotService}, travels in a Telegram {@code /start} payload and is
 * looked up by that value, so a surrogate key would buy nothing.
 *
 * <p>Index {@code (owner_user_id, status)} for matching and {@code (status, expires_at)}
 * for the retention purge on the concrete table; {@code bot_user_id} needs a unique
 * index over its non-null values, which is what stops two intents from claiming one bot.
 */
@MappedSuperclass
public abstract class BaseManagedBotIntent {

    @Id
    @Column(name = "id", length = 32, nullable = false)
    private String id;

    @Column(name = "suggested_username", length = 50)
    private String suggestedUsername;

    @Column(name = "suggested_name", length = 100)
    private String suggestedName;

    @Column(name = "host_ref", length = 128)
    private String hostRef;

    @Column(name = "owner_user_id")
    private Long ownerUserId;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", length = 16, nullable = false)
    private ManagedBotIntentStatus status;

    @Column(name = "bot_user_id", unique = true)
    private Long botUserId;

    @Column(name = "created_at", nullable = false)
    private OffsetDateTime createdAt = OffsetDateTime.now();

    @Column(name = "claimed_at")
    private OffsetDateTime claimedAt;

    @Column(name = "completed_at")
    private OffsetDateTime completedAt;

    @Column(name = "expires_at", nullable = false)
    private OffsetDateTime expiresAt;

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }
    public String getSuggestedUsername() { return suggestedUsername; }
    public void setSuggestedUsername(String suggestedUsername) { this.suggestedUsername = suggestedUsername; }
    public String getSuggestedName() { return suggestedName; }
    public void setSuggestedName(String suggestedName) { this.suggestedName = suggestedName; }
    public String getHostRef() { return hostRef; }
    public void setHostRef(String hostRef) { this.hostRef = hostRef; }
    public Long getOwnerUserId() { return ownerUserId; }
    public void setOwnerUserId(Long ownerUserId) { this.ownerUserId = ownerUserId; }
    public ManagedBotIntentStatus getStatus() { return status; }
    public void setStatus(ManagedBotIntentStatus status) { this.status = status; }
    public Long getBotUserId() { return botUserId; }
    public void setBotUserId(Long botUserId) { this.botUserId = botUserId; }
    public OffsetDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(OffsetDateTime createdAt) { this.createdAt = createdAt; }
    public OffsetDateTime getClaimedAt() { return claimedAt; }
    public void setClaimedAt(OffsetDateTime claimedAt) { this.claimedAt = claimedAt; }
    public OffsetDateTime getCompletedAt() { return completedAt; }
    public void setCompletedAt(OffsetDateTime completedAt) { this.completedAt = completedAt; }
    public OffsetDateTime getExpiresAt() { return expiresAt; }
    public void setExpiresAt(OffsetDateTime expiresAt) { this.expiresAt = expiresAt; }
}
